// ============================================================================
// Recent Advances in Transformer Architectures — A Survey
// Generated by: academic-paper-writer SKILL (Typst-first workflow)
// Domain: computer-science | Format: typst | Citation style: ieee
// ============================================================================

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
  numbering: "1",
)

#set text(
  font: ("Libertinus Serif", "Noto Serif CJK SC"),
  size: 11pt,
  lang: "en",
)

#set par(
  justify: true,
  leading: 0.65em,
  first-line-indent: 0pt,
  spacing: 6pt,
)

#bibliography("ref.bib", style: "ieee")

#show heading.where(level: 1): set text(size: 16pt, weight: "bold")
#show heading.where(level: 1): set block(spacing: 18pt)
#show heading.where(level: 2): set text(size: 13pt, weight: "bold")
#show heading.where(level: 2): set block(spacing: 12pt)

#set heading(numbering: "1. 1.1 1.1.1")

// ---------------------------------------------------------------------------
#align(center, [
  #text(size: 20pt, weight: "bold")[Recent Advances in Transformer Architectures: A Survey]

  #v(0.8em)
  #text(size: 12pt, fill: gray)[Author Name#super[1], Collaborator Name#super[2]]
  #v(0.4em)
  #text(size: 9pt, fill: gray)[
    #super[1] Department of Computer Science, Example University \
    #super[2] AI Research Lab, Example Institute
  ]
  #v(1.5em)
])

#text(size: 10pt, weight: "bold")[Keywords:] #text(size: 10pt)[transformer, attention mechanism, large language models, vision transformers, efficient transformers]

#block(
  fill: luma(245),
  inset: 12pt,
  radius: 4pt,
  [
    = Abstract
    The Transformer architecture @vaswani2017attention has become the dominant paradigm across natural language processing, computer vision, and multi-modal learning. This survey reviews recent advances in Transformer architectures published between 2019 and 2024. We cover three major dimensions: pre-training methodologies that enable transfer learning at scale @devlin2019bert @raffel2020exploring, architectural innovations that extend Transformers beyond text to vision and multi-modal domains @dosovitskiy2021image @liu2021swin, and efficiency improvements that address the quadratic complexity of self-attention @dao2022flashattention. We also examine scaling trends that have driven the emergence of large language models @kaplan2020scaling @brown2020language @touvron2023llama @achiam2023gpt4. Our analysis identifies key design patterns and open challenges, including context length limitations, training stability, and inference efficiency.
  ],
)

#pagebreak()

// ============================================================================
= Introduction

The Transformer architecture, introduced by Vaswani et al. @vaswani2017attention, replaced recurrent and convolutional sequence models with a purely attention-based mechanism. Its key innovation — multi-head scaled dot-product attention — enables parallel computation across input tokens while capturing long-range dependencies through learned pairwise interactions.

Since its introduction, Transformers have driven breakthrough results across a remarkable range of domains. In natural language processing, pre-trained Transformer models such as BERT @devlin2019bert and GPT-3 @brown2020language established new state-of-the-art results across dozens of benchmarks. In computer vision, the Vision Transformer (ViT) @dosovitskiy2021image demonstrated that pure Transformer architectures can match or exceed convolutional networks when trained on sufficient data, while hierarchical designs such as the Swin Transformer @liu2021swin improved efficiency for dense prediction tasks.

This survey provides a structured overview of recent advances in Transformer architectures. We organize our discussion around three complementary perspectives: pre-training and transfer learning (Section 2), domain-specific architectural adaptations (Section 3), and efficiency improvements (Section 4). For each area, we identify key design principles, compare representative models, and highlight open research challenges.

// ============================================================================
= Pre-Training and Transfer Learning

Pre-training has been the primary driver of Transformer adoption. The core idea — train a large model on a self-supervised objective using vast unlabeled corpora, then fine-tune on downstream tasks — was popularized by BERT @devlin2019bert and has since become the standard paradigm.

BERT introduced masked language modeling (MLM), where a fraction of input tokens are replaced with a `[MASK]` token and the model is trained to recover the originals. This bidirectional objective proved substantially more effective than the left-to-right language modeling used by earlier models. The T5 model @raffel2020exploring unified diverse NLP tasks into a text-to-text format, demonstrating that a single pre-trained encoder-decoder Transformer could handle translation, summarization, question answering, and classification with a consistent interface.

Scaling has emerged as a critical axis of progress. Kaplan et al. @kaplan2020scaling established power-law relationships between model size, dataset size, and performance, providing a theoretical framework for the scaling hypothesis. GPT-3 @brown2020language applied these principles at unprecedented scale — 175 billion parameters — and demonstrated emergent few-shot learning capabilities: the ability to perform novel tasks from only a handful of examples without gradient updates. More recently, open-weight models such as LLaMA @touvron2023llama have shown that competitive performance can be achieved at smaller scales through careful data curation and longer training, while GPT-4 @achiam2023gpt4 has pushed the frontier further with multi-modal capabilities and improved instruction following.

// ============================================================================
= Architectural Adaptations Beyond Text

The Transformer's sequence-to-sequence design proved remarkably adaptable to non-text modalities. The Vision Transformer (ViT) @dosovitskiy2021image demonstrated that by splitting an image into fixed-size patches and treating each patch as a token, a standard Transformer encoder could achieve competitive results on image classification. While ViT required large-scale pre-training (e.g., JFT-300M) to match convolutional networks, subsequent work on data-efficient training and hybrid architectures has reduced this dependency.

For dense vision tasks such as object detection and semantic segmentation, hierarchical Transformers have become the dominant approach. The Swin Transformer @liu2021swin introduced shifted window attention, which computes self-attention within local windows while allowing cross-window communication through window shifting between layers. This design achieves linear complexity relative to image resolution while maintaining the ability to model long-range spatial dependencies. The resulting architecture has been widely adopted as a backbone for detection, segmentation, and video understanding.

#figure(
  {
    set align(center)
    stack(
      dir: ttb,
      spacing: 8pt,
      block(width: 100%, fill: rgb("#e3f2fd"), stroke: 1pt + rgb("#1976d2"), radius: 4pt, inset: 8pt)[*Input Tokens* (text / image patches / audio frames)],
      text(size: 14pt)[↓],
      block(width: 100%, fill: rgb("#e8f5e9"), stroke: 1pt + rgb("#388e3c"), radius: 4pt, inset: 8pt)[*Multi-Head Self-Attention* + Feed-Forward Network × N layers],
      text(size: 14pt)[↓],
      block(width: 100%, fill: rgb("#fff3e0"), stroke: 1pt + rgb("#f57c00"), radius: 4pt, inset: 8pt)[*Task-Specific Head* (classification / generation / detection)],
    )
  },
  caption: [Generic Transformer architecture. Input tokens pass through N stacked self-attention and feed-forward layers, followed by a task-specific prediction head. Adapted from @vaswani2017attention.],
) <fig-transformer-arch>

The unified sequence-to-sequence abstraction — where any modality is tokenized and processed by the same Transformer backbone — has also enabled multi-modal models. GPT-4 @achiam2023gpt4 accepts interleaved text and image inputs, while research on unified vision-language architectures continues to expand the range of supported modalities.

// ============================================================================
= Efficient Attention Mechanisms

A fundamental limitation of the standard Transformer is the quadratic complexity of self-attention: for a sequence of length n, computing attention scores requires O(n superscript 2) time and memory. This has motivated an active line of research on efficient attention mechanisms.

FlashAttention @dao2022flashattention addresses this problem at the systems level rather than through algorithmic approximation. By carefully tiling the attention computation to maximize on-chip SRAM usage and minimize reads from high-bandwidth memory (HBM), FlashAttention achieves exact attention with significantly reduced memory footprint and wall-clock time. The technique has been widely adopted in major training frameworks and has enabled training on longer sequences with larger models.

Complementary approaches include sparse attention patterns that restrict each token to attend only to a local window or a set of pre-selected global tokens, linearized attention that approximates the softmax kernel, and state-space models that replace attention entirely with structured recurrent computations. Each approach trades off between computational efficiency and modeling capacity, and the optimal choice depends on sequence length, task requirements, and hardware constraints.

#figure(
  table(
    columns: (1.5fr, 1fr, 1fr, 1fr, 1.5fr),
    align: (left, center, center, center, left),
    table.header([*Model*], [*Year*], [*Parameters*], [*Context*], [*Key Innovation*]),
    [BERT @devlin2019bert], [2019], [340M], [512], [Bidirectional MLM pre-training],
    [GPT-3 @brown2020language], [2020], [175B], [2048], [In-context few-shot learning],
    [T5 @raffel2020exploring], [2020], [11B], [512], [Text-to-text unified framework],
    [ViT @dosovitskiy2021image], [2021], [632M], [—], [Patch-based image Transformer],
    [Swin @liu2021swin], [2021], [197M], [—], [Shifted window attention],
    [LLaMA @touvron2023llama], [2023], [65B], [2048], [Open-weight efficient LLM],
    [GPT-4 @achiam2023gpt4], [2023], [—], [32K], [Multi-modal + instruction following],
  ),
  caption: [Comparison of representative Transformer models discussed in this survey. Parameter counts and context lengths reflect the largest publicly reported configuration for each model.],
) <table-model-comparison>

// ============================================================================
= Conclusion

This survey has reviewed recent advances in Transformer architectures across three complementary dimensions: pre-training methodologies, domain-specific adaptations, and efficiency improvements. The Transformer's core abstraction — representing arbitrary inputs as sequences of tokens processed by stacked self-attention and feed-forward layers — has proven remarkably versatile, enabling breakthroughs in language, vision, and multi-modal learning.

Several open challenges remain. Context length continues to be a limiting factor for long-document understanding and multi-turn dialogue, despite progress in efficient attention @dao2022flashattention and position encoding. Training stability at scale requires careful initialization, learning rate scheduling, and normalization strategies. Inference efficiency for large models — particularly latency-sensitive applications — remains an active area of optimization.

Looking forward, we anticipate continued convergence across modalities toward unified architectures, further improvements in data and compute efficiency, and deeper integration of retrieval and tool-use capabilities into Transformer-based systems @achiam2023gpt4.

// ============================================================================
= Acknowledgments
This example paper was generated using the academic-paper-writer Codex SKILL to demonstrate the Typst-first workflow. Citations reference real publications; the prose is synthetic and intended for illustration purposes only.
